services:
  discordbot:
    build: .
    container_name: python-discord-bot
    restart: always
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - mariadb
    command: ["python", "src/bot.py"]

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql